name: Tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  skip_duplicate_runs:
    uses: ./.github/workflows/skip_duplicate_workflow_runs.yml

  rubocop:
    name: RuboCop linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true # `bundle install` and cache
      - name: rubocop
        run: bundle exec rake rubocop

  test_non_mri:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}${{ matrix.no-ssl }}
    needs: [rubocop, skip_duplicate_runs]
    env:
      CI: true
      PUMA_TEST_DEBUG: true
      TESTOPTS: -v
      PUMA_NO_RUBOCOP: true

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        include:
          # tto - test timeout
          - { tto: 8 , os: ubuntu-22.04 , ruby: jruby }
          - { tto: 8 , os: ubuntu-22.04 , ruby: jruby, no-ssl: ' no SSL' }
          - { tto: 8 , os: ubuntu-22.04 , ruby: jruby-head, allow-failure: true }
          - { tto: 8 , os: ubuntu-20.04 , ruby: truffleruby, allow-failure: true } # Until https://github.com/oracle/truffleruby/issues/2700 is solved
          - { tto: 8 , os: ubuntu-20.04 , ruby: truffleruby-head, allow-failure: true }
          - { tto: 8 , os: ubuntu-22.04 , ruby: truffleruby, allow-failure: true } # Until https://github.com/oracle/truffleruby/issues/2700 is solved
          - { tto: 8 , os: ubuntu-22.04 , ruby: truffleruby-head, allow-failure: true }
          - { tto: 8 , os: macos-13     , ruby: jruby }
          - { tto: 8 , os: macos-14     , ruby: jruby }
          - { tto: 8 , os: macos-13     , ruby: truffleruby, allow-failure: true }

    steps:
      - name: repo checkout
        if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
        uses: actions/checkout@v4

      - name: Set JAVA_HOME
        if: |
          (matrix.ruby == 'jruby-head') &&
          (needs.skip_duplicate_runs.outputs.should_skip != 'true')
        run: |
          echo 'JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64' >> $GITHUB_ENV
          echo 'JAVA_HOME_21_X64=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64' >> $GITHUB_ENV

      - name: load ruby, ragel
        if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel
          bundler: none
          bundler-cache: true
        timeout-minutes: 10

      - name: Compile Puma without SSL support
        if: |
          (matrix.no-ssl == ' no SSL') &&
          (needs.skip_duplicate_runs.outputs.should_skip != 'true')
        shell: bash
        run: echo 'PUMA_DISABLE_SSL=true' >> $GITHUB_ENV

      - name: set WERRORFLAG
        if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
        shell: bash
        run: echo 'PUMA_MAKE_WARNINGS_INTO_ERRORS=true' >> $GITHUB_ENV

      - name: compile
        id: compile
        continue-on-error: ${{ matrix.allow-failure || false }}
        if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
        run:  bundle exec rake compile

      - name: >-
          Compile outcome: ${{ steps.compile.outcome }}
        # every step must define a `uses` or `run` key
        run: echo NOOP

      - name: test
        id: test
        timeout-minutes: ${{ matrix.tto }}
        continue-on-error: ${{ matrix.allow-failure || false }}
        if: | # only run if previous steps have succeeded
          success() &&
          (needs.skip_duplicate_runs.outputs.should_skip != 'true')
        run: test/runner --verbose
        env:
          MT_CPU: 2

      - name: >-
          Test outcome: ${{ steps.test.outcome }}
        # every step must define a `uses` or `run` key
        run: echo NOOP
